import { collection, doc, getDocs, query, where, setDoc, serverTimestamp } from 'firebase/firestore';
import { db } from './config';
import { UserProfile } from '../types';

export const SEED_LISTENERS: Omit<UserProfile, 'uid' | 'created_at'>[] = [
  {
    name: 'Priya Rajendran',
    email: 'priya.listener@meetup.com',
    age: 22,
    gender: 'female',
    location: 'Chennai, Tamil Nadu',
    bio: 'Software engineer by day, friendly listener by evening. Traditional Bharatanatyam dancer who loves modern cinema, Carnatic fusion, and deep conversations over filter coffee.',
    profile_pic: 'https://randomuser.me/api/portraits/women/11.jpg',
    interests: ['Classical Dance', 'Filter Coffee', 'Tech & AI', 'Deep Talks'],
    language: 'ta',
    role: 'listener',
    coins_balance: 120,
    diamonds_balance: 45,
    voice_rate: 20,
    video_rate: 50,
    status: 'online',
    presence_status: 'available',
    is_available: true,
    is_blocked: false,
  },
  {
    name: 'Ananya Sridhar',
    email: 'ananya.listener@meetup.com',
    age: 21,
    gender: 'female',
    location: 'Coimbatore, Tamil Nadu',
    bio: 'Kind-hearted literature grad. Balanced blend of modern cafe culture and traditional Tamil poetry. Let us share laughter, acoustic songs, and calm vibes after a long day.',
    profile_pic: 'https://randomuser.me/api/portraits/women/22.jpg',
    interests: ['Tamil Poetry', 'Books & Novels', 'Acoustic Guitar', 'Mindfulness'],
    language: 'en',
    role: 'listener',
    coins_balance: 200,
    diamonds_balance: 90,
    voice_rate: 25,
    video_rate: 60,
    status: 'online',
    presence_status: 'available',
    is_available: true,
    is_blocked: false,
  },
  {
    name: 'Divya Bharathi',
    email: 'divya.listener@meetup.com',
    age: 20,
    gender: 'female',
    location: 'Madurai, Tamil Nadu',
    bio: 'Madurai ponnu with a contagious smile! College final year student who loves spicy street food, temple architecture, and chatting about college life and dreams.',
    profile_pic: 'https://randomuser.me/api/portraits/women/32.jpg',
    interests: ['Street Food', 'Tamil Cinema', 'College Stories', 'Photography'],
    language: 'ta',
    role: 'listener',
    coins_balance: 80,
    diamonds_balance: 30,
    voice_rate: 20,
    video_rate: 50,
    status: 'busy',
    presence_status: 'busy',
    is_available: true,
    is_blocked: false,
  },
  {
    name: 'Kaviya Murali',
    email: 'kaviya.listener@meetup.com',
    age: 23,
    gender: 'female',
    location: 'Trichy, Tamil Nadu',
    bio: 'Certified yoga instructor and wellness podcaster. Calm, grounded, and empathetic. Here to listen whenever you need a soothing voice or an open non-judgmental space.',
    profile_pic: 'https://randomuser.me/api/portraits/women/44.jpg',
    interests: ['Yoga', 'Mental Wellness', 'Nature Walks', 'Meditation'],
    language: 'ta',
    role: 'listener',
    coins_balance: 150,
    diamonds_balance: 60,
    voice_rate: 20,
    video_rate: 45,
    status: 'online',
    presence_status: 'available',
    is_available: true,
    is_blocked: false,
  },
  {
    name: 'Meena Sundaram',
    email: 'meena.listener@meetup.com',
    age: 19,
    gender: 'female',
    location: 'Salem, Tamil Nadu',
    bio: 'Fine arts student & modern graphic designer. Passionate about retro Ilayaraja tunes, nighttime sketching, and heartwarming life stories.',
    profile_pic: 'https://randomuser.me/api/portraits/women/47.jpg',
    interests: ['Retro Music', 'Graphic Design', 'Night Owl', 'Art & Sketching'],
    language: 'ta',
    role: 'listener',
    coins_balance: 95,
    diamonds_balance: 25,
    voice_rate: 22,
    video_rate: 55,
    status: 'offline',
    presence_status: 'unavailable',
    is_available: false,
    is_blocked: false,
  },
  {
    name: 'Deepa Krishnan',
    email: 'deepa.listener@meetup.com',
    age: 21,
    gender: 'female',
    location: 'Tirunelveli, Tamil Nadu',
    bio: 'Sweet halwa city native speaking fluent Tamil & Telugu. Upbeat, caring, and loves talking about music, celebrations, fashion, and everyday happiness.',
    profile_pic: 'https://randomuser.me/api/portraits/women/57.jpg',
    interests: ['Dance', 'Tamil & Telugu Hits', 'Fashion', 'Celebrations'],
    language: 'te',
    role: 'listener',
    coins_balance: 60,
    diamonds_balance: 15,
    voice_rate: 20,
    video_rate: 50,
    status: 'online',
    presence_status: 'available',
    is_available: true,
    is_blocked: false,
  },
  {
    name: 'Nivetha Ramesh',
    email: 'nivetha.listener@meetup.com',
    age: 24,
    gender: 'female',
    location: 'Vellore, Tamil Nadu',
    bio: 'Tech professional who loves mentoring and friendly chats. A thoughtful listener who can give you warm perspective on career stress or life crossroads.',
    profile_pic: 'https://randomuser.me/api/portraits/women/62.jpg',
    interests: ['Self-Growth', 'Podcasts', 'Tea Sessions', 'Life Advice'],
    language: 'en',
    role: 'listener',
    coins_balance: 310,
    diamonds_balance: 140,
    voice_rate: 30,
    video_rate: 70,
    status: 'online',
    presence_status: 'available',
    is_available: true,
    is_blocked: false,
  },
  {
    name: 'Harini Venkatesh',
    email: 'harini.listener@meetup.com',
    age: 22,
    gender: 'female',
    location: 'Erode, Tamil Nadu',
    bio: 'Home baker and foodie with a golden heart. Loves exchanging recipes, funny memories, and listening to people from all walks of life.',
    profile_pic: 'https://randomuser.me/api/portraits/women/65.jpg',
    interests: ['Baking', 'Traditional Recipes', 'Humor', 'Gardening'],
    language: 'ta',
    role: 'listener',
    coins_balance: 110,
    diamonds_balance: 40,
    voice_rate: 20,
    video_rate: 50,
    status: 'online',
    presence_status: 'available',
    is_available: true,
    is_blocked: false,
  },
  {
    name: 'Sneha Balan',
    email: 'sneha.listener@meetup.com',
    age: 23,
    gender: 'female',
    location: 'Tiruppur, Tamil Nadu',
    bio: 'Textile styling graduate with high energy and cheerful vibes. Whether you want a friendly banter or deep venting, I am always right here!',
    profile_pic: 'https://randomuser.me/api/portraits/women/68.jpg',
    interests: ['Ethnic Wear', 'Travel', 'Banter', 'Pop Culture'],
    language: 'hi',
    role: 'listener',
    coins_balance: 180,
    diamonds_balance: 75,
    voice_rate: 25,
    video_rate: 60,
    status: 'busy',
    presence_status: 'busy',
    is_available: true,
    is_blocked: false,
  },
  {
    name: 'Keerthana Natarajan',
    email: 'keerthana.listener@meetup.com',
    age: 24,
    gender: 'female',
    location: 'Thanjavur, Tamil Nadu',
    bio: 'Veena player & traditional storyteller from Thanjavur. Modern outlook with deep roots in heritage, art, and nostalgic conversations.',
    profile_pic: 'https://randomuser.me/api/portraits/women/71.jpg',
    interests: ['Carnatic Veena', 'Heritage', 'Storytelling', 'South Indian Art'],
    language: 'ta',
    role: 'listener',
    coins_balance: 140,
    diamonds_balance: 55,
    voice_rate: 20,
    video_rate: 50,
    status: 'online',
    presence_status: 'available',
    is_available: true,
    is_blocked: false,
  },
  {
    name: 'Swathi Govind',
    email: 'swathi.listener@meetup.com',
    age: 20,
    gender: 'female',
    location: 'Dindigul, Tamil Nadu',
    bio: 'Bubbly college student speaking Malayalam and Tamil. Huge fan of anime, campus humor, and late night discussions. No awkward silences with me!',
    profile_pic: 'https://randomuser.me/api/portraits/women/75.jpg',
    interests: ['Anime & Manga', 'Memes', 'Music Streaming', 'Gaming'],
    language: 'ml',
    role: 'listener',
    coins_balance: 90,
    diamonds_balance: 35,
    voice_rate: 20,
    video_rate: 50,
    status: 'online',
    presence_status: 'available',
    is_available: true,
    is_blocked: false,
  },
  {
    name: 'Bhavani Subramaniam',
    email: 'bhavani.listener@meetup.com',
    age: 24,
    gender: 'female',
    location: 'Kanchipuram, Tamil Nadu',
    bio: 'Silk saree lover and patient soul. Gentle, observant, and respectful. An understanding companion for all your emotional highs and lows.',
    profile_pic: 'https://randomuser.me/api/portraits/women/79.jpg',
    interests: ['Traditional Weaves', 'Classical Songs', 'Philosophy', 'Calm Talks'],
    language: 'ta',
    role: 'listener',
    coins_balance: 220,
    diamonds_balance: 105,
    voice_rate: 25,
    video_rate: 65,
    status: 'offline',
    presence_status: 'unavailable',
    is_available: false,
    is_blocked: false,
  },
  {
    name: 'Shalini Murugan',
    email: 'shalini.listener@meetup.com',
    age: 21,
    gender: 'female',
    location: 'Puducherry',
    bio: 'French colony girl with a love for ocean sunsets, acoustic indie bands, and cycling along Promenade Beach. Cheerful, modern, and easy-going.',
    profile_pic: 'https://randomuser.me/api/portraits/women/83.jpg',
    interests: ['Beach Sunsets', 'Indie Music', 'Cycling', 'French & Tamil'],
    language: 'ta',
    role: 'listener',
    coins_balance: 130,
    diamonds_balance: 50,
    voice_rate: 22,
    video_rate: 55,
    status: 'online',
    presence_status: 'available',
    is_available: true,
    is_blocked: false,
  },
  {
    name: 'Yamuna Selvam',
    email: 'yamuna.listener@meetup.com',
    age: 22,
    gender: 'female',
    location: 'Nagercoil, Tamil Nadu',
    bio: 'Southern tip adventurer surrounded by Western Ghats. Loves talking about nature trips, local traditions, coffee, and quiet rainy evenings.',
    profile_pic: 'https://randomuser.me/api/portraits/women/86.jpg',
    interests: ['Hill Treks', 'Rainy Days', 'Nature', 'Coffee Chats'],
    language: 'ta',
    role: 'listener',
    coins_balance: 160,
    diamonds_balance: 65,
    voice_rate: 20,
    video_rate: 50,
    status: 'online',
    presence_status: 'available',
    is_available: true,
    is_blocked: false,
  },
  {
    name: 'Madhumitha Raj',
    email: 'madhumitha.listener@meetup.com',
    age: 19,
    gender: 'female',
    location: 'Kumbakonam, Tamil Nadu',
    bio: 'Temple town college student with traditional roots and modern dreams. Loves classical Carnatic music, spicy snacks, and hearty heartfelt talks.',
    profile_pic: 'https://randomuser.me/api/portraits/women/90.jpg',
    interests: ['Carnatic Songs', 'Traditional Snacking', 'College Life', 'Friendship'],
    language: 'ta',
    role: 'listener',
    coins_balance: 100,
    diamonds_balance: 40,
    voice_rate: 20,
    video_rate: 50,
    status: 'online',
    presence_status: 'available',
    is_available: true,
    is_blocked: false,
  },
];

export async function seedFirestoreDatabase(forceRefresh = false): Promise<void> {
  try {
    const usersRef = collection(db, 'users');
    const q = query(usersRef, where('role', '==', 'listener'));
    const snapshot = await getDocs(q);

    // If fewer than 15 listeners exist or force refresh requested, seed the 15 profiles
    if (snapshot.size < 15 || forceRefresh) {
      console.log('Seeding 15 real South Indian female listener profiles...');
      for (let i = 0; i < SEED_LISTENERS.length; i++) {
        const listener = SEED_LISTENERS[i];
        const docId = `listener_seed_${i + 1}`;
        await setDoc(
          doc(db, 'users', docId),
          {
            ...listener,
            uid: docId,
            role: 'listener',
            audio_rate_coins: listener.audio_rate_coins ?? listener.voice_rate ?? 20,
            video_rate_coins: listener.video_rate_coins ?? listener.video_rate ?? 50,
            isBlocked: false,
            is_blocked: false,
            password_hash: 'seed_encrypted_hash',
            created_at: serverTimestamp(),
            createdAt: serverTimestamp(),
          },
          { merge: true }
        );
      }
      console.log('15 Listener profiles seeded successfully with real Indian portraits.');
    }

    // Also seed default admin user document if not existing
    const adminDocRef = doc(db, 'users', 'admin_meetup_uid');
    await setDoc(
      adminDocRef,
      {
        uid: 'admin_meetup_uid',
        name: 'Meet Up Admin',
        email: 'admin@meetup.com',
        age: 26,
        gender: 'female',
        location: 'Chennai, Tamil Nadu',
        bio: 'Meet Up Platform Super Administrator',
        profile_pic: 'https://randomuser.me/api/portraits/women/62.jpg',
        interests: ['Platform Safety', 'Moderation', 'Community'],
        language: 'en',
        role: 'admin',
        coins_balance: 9999,
        diamonds_balance: 500,
        voice_rate: 20,
        video_rate: 50,
        status: 'online',
        is_blocked: false,
        created_at: serverTimestamp(),
      },
      { merge: true }
    );
  } catch (error) {
    console.error('Error during Firestore database seeding:', error);
  }
}
